on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
- name: Checkout code
  uses: actions/checkout@v3
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'
- name: Install Trivy
  run: |
    sudo apt-get update
    sudo apt-get install -y wget
    wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.43.2_Linux-64bit.deb
    sudo dpkg -i trivy_0.43.2_Linux-64bit.deb
- name: Install Syft and Cosign
  run: |
    curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    curl -sSL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
    chmod +x /usr/local/bin/cosign
- name: Install Semgrep
  run: pip install semgrep
- name: Install Safety
  run: pip install safety
- name: Install Gitleaks
  run: |
    curl -sSL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks_8.21.0_linux_x64.tar.gz | tar xz
    sudo mv gitleaks /usr/local/bin/
- name: Run Unit Tests
  run: |
    pip install -r requirements.txt
    pytest tests/ --junitxml=unit-test-report.xml
- name: Run SAST Scan
  run: semgrep --config "p/ci"
- name: Run SCA Scan
  run: safety check
- name: Run Secret Scan
  run: gitleaks detect --source .
- name: Build Docker Image
  run: docker build -t myapp:latest .

- name: Scan Docker Image with Trivy
  run: trivy image --severity HIGH,CRITICAL myapp:latest
- name: Generate SBOM
  run: syft packages dir:. -o json > sbom.json

- name: Sign SBOM
  run: cosign sign-blob sbom.json
- name: Run DAST Scan
  uses: zaproxy/action-full-scan@v1
  with:
    target: 'http://localhost:8000'
- name: Upload Artefacts
  uses: actions/upload-artifact@v3
  with:
    name: secure-pipeline-reports
    path: |
      sbom.json
      unit-test-report.xml
      trivy-report.json
